[tool.poetry]
name = "music-blog"
version = "0.1.0"
description = ""
authors = ["Aleksandr Kropanev <kropanev@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.9"
SQLAlchemy = "^1.3.20"

[tool.poetry.dev-dependencies]
pytest = "^6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
